swagger: "2.0"
info:
  description: "A simple contacts API, where a user can get a quick overview of all contacts resources like person, skills."
  version: "1.0.0"
  title: "Contacts API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "stephaneselim94@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/api"
tags:
  - name: "user"
    description: "Everything about users"
  - name: "contact"
    description: "Access to a person's contact"
  - name: "skill"
    description: "Access to a person's skills"
schemes:
  - "http"
paths:
  /contacts:
    get:
      tags:
        - "contact"
      summary: "Get all contacts"
      description: "Get the contacts of everyone"
      operationId: "getContacts"
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Contact"

  /skills:
    get:
      tags:
        - "skill"
      summary: "Get all skills"
      description: "Get all available skills"
      operationId: "getSkills"
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Skill"
definitions:
  Contact:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      fullName:
        type: "string"
      address:
        type: "string"
      email:
        type: "string"
      phoneNumber:
        type: "string"
  Skill:
    type: "object"
    properties:
      skill:
        type: "string"
  SkilledContact:
    type: "object"
    properties:
      contactId:
        type: "integer"
        format: "int64"
      skill:
        type: "string"
      level:
        type: "string"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"